-- =============================================================
-- Tech-Cup DOSW 2026-1 - Schema completo para Supabase (PostgreSQL)
-- Ejecutar este script en el SQL Editor de Supabase
-- =============================================================

-- =====================
-- 1. USUARIOS Y AUTH
-- =====================

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50),
    user_type VARCHAR(50),
    program VARCHAR(100),
    identification VARCHAR(255),
    relationship_type VARCHAR(255),
    relationship_description VARCHAR(500),
    avatar_url VARCHAR(1024),
    active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sport_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    position VARCHAR(50),
    secondary_position VARCHAR(50),
    dominant_foot VARCHAR(20),
    program VARCHAR(100),
    jersey_number INTEGER,
    photo_url VARCHAR(255),
    full_photo_url VARCHAR(1024),
    available BOOLEAN DEFAULT true,
    semester INTEGER,
    gender VARCHAR(50),
    age INTEGER,
    last_availability_change TIMESTAMP,
    availability_change_reason VARCHAR(255),
    CONSTRAINT fk_sport_profile_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS verification_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    verified_at TIMESTAMP,
    verified BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT fk_verification_token_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP,
    used BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT fk_password_reset_token_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS revoked_refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(2048) NOT NULL UNIQUE,
    revoked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =====================
-- 1.5. RBAC (ROLES Y PERMISOS)
-- =====================

CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(80) NOT NULL UNIQUE,
    module VARCHAR(60) NOT NULL,
    description VARCHAR(255),
    active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
    CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
);

INSERT INTO roles (code, name, description) VALUES
('PLAYER', 'Jugador', 'Participante del torneo con acceso limitado a sus propios recursos'),
('CAPTAIN', 'Capitan', 'Jugador con permisos de gestion sobre su equipo'),
('ORGANIZER', 'Organizador', 'Gestion operativa del torneo y sus configuraciones'),
('REFEREE', 'Arbitro', 'Gestion de actas, eventos y sanciones en partidos'),
('ADMINISTRATOR', 'Administrador', 'Control total del sistema y de permisos')
ON CONFLICT (code) DO NOTHING;

INSERT INTO permissions (code, module, description) VALUES
('AUTH_REGISTER', 'AUTH', 'Registrar usuarios'),
('AUTH_LOGIN', 'AUTH', 'Iniciar sesion'),
('AUTH_LOGOUT', 'AUTH', 'Cerrar sesion'),
('AUTH_REFRESH_TOKEN', 'AUTH', 'Renovar token de acceso'),
('AUTH_RECOVER_PASSWORD', 'AUTH', 'Recuperar contrasena'),
('AUTH_VERIFY_EMAIL', 'AUTH', 'Verificar correo'),
('USER_READ', 'USER', 'Consultar usuarios'),
('USER_CREATE', 'USER', 'Crear usuarios'),
('USER_UPDATE', 'USER', 'Actualizar usuarios'),
('USER_DELETE', 'USER', 'Eliminar usuarios'),
('USER_ASSIGN_ROLE', 'USER', 'Asignar rol de usuario'),
('PROFILE_READ_OWN', 'PROFILE', 'Consultar perfil propio'),
('PROFILE_UPDATE_OWN', 'PROFILE', 'Actualizar perfil propio'),
('PROFILE_UPLOAD_AVATAR', 'PROFILE', 'Cargar avatar'),
('PROFILE_UPLOAD_FULL_PHOTO', 'PROFILE', 'Cargar foto de cuerpo completo'),
('USER_STATS_READ', 'PROFILE', 'Consultar estadisticas de usuario'),
('TOURNAMENT_CREATE', 'TOURNAMENT', 'Crear torneo'),
('TOURNAMENT_UPDATE', 'TOURNAMENT', 'Actualizar torneo'),
('TOURNAMENT_DELETE', 'TOURNAMENT', 'Eliminar torneo'),
('TOURNAMENT_READ', 'TOURNAMENT', 'Consultar torneos'),
('TOURNAMENT_CONFIRM_RULES', 'TOURNAMENT', 'Confirmar reglas de torneo'),
('TOURNAMENT_VIEW_BRACKET', 'TOURNAMENT', 'Consultar llaves de eliminacion'),
('TOURNAMENT_VIEW_STANDINGS', 'TOURNAMENT', 'Consultar tabla de posiciones'),
('TEAM_CREATE', 'TEAM', 'Crear equipo'),
('TEAM_UPDATE', 'TEAM', 'Actualizar equipo'),
('TEAM_DELETE', 'TEAM', 'Eliminar equipo'),
('TEAM_READ', 'TEAM', 'Consultar equipos'),
('TEAM_MANAGE_PLAYERS', 'TEAM', 'Gestionar jugadores de equipo'),
('TEAM_VIEW_OWN', 'TEAM', 'Consultar equipo propio'),
('INVITATION_READ', 'INVITATION', 'Consultar invitaciones'),
('INVITATION_SEND', 'INVITATION', 'Enviar invitaciones'),
('INVITATION_ACCEPT', 'INVITATION', 'Aceptar invitaciones'),
('INVITATION_REJECT', 'INVITATION', 'Rechazar invitaciones'),
('INVITATION_DELETE', 'INVITATION', 'Eliminar invitaciones'),
('MATCH_CREATE', 'MATCH', 'Crear partido'),
('MATCH_UPDATE', 'MATCH', 'Actualizar partido'),
('MATCH_DELETE', 'MATCH', 'Eliminar partido'),
('MATCH_READ', 'MATCH', 'Consultar partidos'),
('MATCH_CHANGE_STATUS', 'MATCH', 'Cambiar estado de partido'),
('RESULT_REGISTER', 'RESULT', 'Registrar resultado'),
('GOAL_REGISTER', 'RESULT', 'Registrar goles'),
('CARD_REGISTER', 'RESULT', 'Registrar tarjetas'),
('POSSESSION_REGISTER', 'RESULT', 'Registrar posesion'),
('RESULT_READ', 'RESULT', 'Consultar resultados'),
('LINEUP_CREATE', 'LINEUP', 'Crear alineacion'),
('LINEUP_UPDATE', 'LINEUP', 'Actualizar alineacion'),
('LINEUP_DELETE', 'LINEUP', 'Eliminar alineacion'),
('LINEUP_READ', 'LINEUP', 'Consultar alineaciones'),
('PAYMENT_REGISTER', 'PAYMENT', 'Registrar pago'),
('PAYMENT_READ', 'PAYMENT', 'Consultar pagos'),
('PAYMENT_UPDATE', 'PAYMENT', 'Actualizar pago'),
('PAYMENT_DELETE', 'PAYMENT', 'Eliminar pago'),
('SANCTION_CREATE', 'SANCTION', 'Crear sancion'),
('SANCTION_UPDATE', 'SANCTION', 'Actualizar sancion'),
('SANCTION_DELETE', 'SANCTION', 'Eliminar sancion'),
('SANCTION_READ', 'SANCTION', 'Consultar sanciones'),
('REPORT_READ_STATS', 'REPORT', 'Consultar estadisticas generales'),
('REPORT_READ_TOP_SCORERS', 'REPORT', 'Consultar goleadores'),
('REPORT_READ_MATCH_HISTORY', 'REPORT', 'Consultar historial de partidos'),
('REPORT_READ_PERFORMANCE', 'REPORT', 'Consultar rendimiento'),
('NOTIFICATION_READ', 'NOTIFICATION', 'Consultar notificaciones'),
('NOTIFICATION_READ_COUNT', 'NOTIFICATION', 'Consultar contador de notificaciones'),
('NOTIFICATION_SEND_EMAIL', 'NOTIFICATION', 'Enviar notificaciones por correo'),
('AUDIT_READ', 'ADMIN', 'Consultar auditoria'),
('AUDIT_DELETE', 'ADMIN', 'Eliminar auditoria'),
('SYSTEM_MANAGE', 'ADMIN', 'Gestionar parametros del sistema'),
('BACKEND_VALIDATE', 'ADMIN', 'Validaciones internas de backend'),
('ACCESS_CONTROL_MANAGE', 'ADMIN', 'Gestionar control de acceso')
ON CONFLICT (code) DO NOTHING;

-- ADMINISTRATOR = todos los permisos
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
CROSS JOIN permissions p
WHERE r.code = 'ADMINISTRATOR'
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- ORGANIZER
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code IN (
    'AUTH_REGISTER','AUTH_LOGIN','AUTH_LOGOUT','AUTH_REFRESH_TOKEN','AUTH_RECOVER_PASSWORD','AUTH_VERIFY_EMAIL',
    'USER_READ','USER_UPDATE','PROFILE_READ_OWN','PROFILE_UPDATE_OWN','PROFILE_UPLOAD_AVATAR','PROFILE_UPLOAD_FULL_PHOTO','USER_STATS_READ',
    'TOURNAMENT_CREATE','TOURNAMENT_UPDATE','TOURNAMENT_DELETE','TOURNAMENT_READ','TOURNAMENT_CONFIRM_RULES','TOURNAMENT_VIEW_BRACKET','TOURNAMENT_VIEW_STANDINGS',
    'TEAM_CREATE','TEAM_UPDATE','TEAM_DELETE','TEAM_READ','TEAM_MANAGE_PLAYERS','TEAM_VIEW_OWN',
    'INVITATION_READ','INVITATION_SEND','INVITATION_ACCEPT','INVITATION_REJECT','INVITATION_DELETE',
    'MATCH_CREATE','MATCH_UPDATE','MATCH_DELETE','MATCH_READ','MATCH_CHANGE_STATUS',
    'RESULT_REGISTER','POSSESSION_REGISTER','RESULT_READ',
    'PAYMENT_REGISTER','PAYMENT_READ','PAYMENT_UPDATE','PAYMENT_DELETE',
    'SANCTION_CREATE','SANCTION_UPDATE','SANCTION_READ',
    'REPORT_READ_STATS','REPORT_READ_TOP_SCORERS','REPORT_READ_MATCH_HISTORY','REPORT_READ_PERFORMANCE',
    'NOTIFICATION_READ','NOTIFICATION_READ_COUNT','NOTIFICATION_SEND_EMAIL',
    'AUDIT_READ','SYSTEM_MANAGE','BACKEND_VALIDATE'
)
WHERE r.code = 'ORGANIZER'
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- CAPTAIN
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code IN (
    'AUTH_REGISTER','AUTH_LOGIN','AUTH_LOGOUT','AUTH_REFRESH_TOKEN','AUTH_RECOVER_PASSWORD','AUTH_VERIFY_EMAIL',
    'USER_READ','USER_UPDATE','PROFILE_READ_OWN','PROFILE_UPDATE_OWN','PROFILE_UPLOAD_AVATAR','PROFILE_UPLOAD_FULL_PHOTO','USER_STATS_READ',
    'TOURNAMENT_READ','TOURNAMENT_CONFIRM_RULES','TOURNAMENT_VIEW_BRACKET','TOURNAMENT_VIEW_STANDINGS',
    'TEAM_CREATE','TEAM_UPDATE','TEAM_READ','TEAM_MANAGE_PLAYERS','TEAM_VIEW_OWN',
    'INVITATION_READ','INVITATION_SEND','INVITATION_ACCEPT','INVITATION_REJECT',
    'MATCH_READ','RESULT_READ',
    'LINEUP_CREATE','LINEUP_UPDATE','LINEUP_READ',
    'PAYMENT_READ','SANCTION_READ',
    'REPORT_READ_STATS','REPORT_READ_TOP_SCORERS','REPORT_READ_MATCH_HISTORY','REPORT_READ_PERFORMANCE',
    'NOTIFICATION_READ','NOTIFICATION_READ_COUNT','BACKEND_VALIDATE'
)
WHERE r.code = 'CAPTAIN'
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- REFEREE
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code IN (
    'AUTH_REGISTER','AUTH_LOGIN','AUTH_LOGOUT','AUTH_REFRESH_TOKEN','AUTH_RECOVER_PASSWORD','AUTH_VERIFY_EMAIL',
    'USER_READ','PROFILE_READ_OWN','PROFILE_UPDATE_OWN','PROFILE_UPLOAD_AVATAR','PROFILE_UPLOAD_FULL_PHOTO','USER_STATS_READ',
    'TOURNAMENT_READ','TOURNAMENT_CONFIRM_RULES','TOURNAMENT_VIEW_BRACKET','TOURNAMENT_VIEW_STANDINGS',
    'TEAM_READ','TEAM_VIEW_OWN',
    'INVITATION_READ',
    'MATCH_READ','MATCH_CHANGE_STATUS',
    'RESULT_REGISTER','GOAL_REGISTER','CARD_REGISTER','POSSESSION_REGISTER','RESULT_READ',
    'LINEUP_READ',
    'PAYMENT_READ',
    'SANCTION_CREATE','SANCTION_UPDATE','SANCTION_READ',
    'REPORT_READ_STATS','REPORT_READ_TOP_SCORERS','REPORT_READ_MATCH_HISTORY','REPORT_READ_PERFORMANCE',
    'NOTIFICATION_READ','NOTIFICATION_READ_COUNT','BACKEND_VALIDATE'
)
WHERE r.code = 'REFEREE'
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- PLAYER
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code IN (
    'AUTH_REGISTER','AUTH_LOGIN','AUTH_LOGOUT','AUTH_REFRESH_TOKEN','AUTH_RECOVER_PASSWORD','AUTH_VERIFY_EMAIL',
    'USER_READ','USER_UPDATE','PROFILE_READ_OWN','PROFILE_UPDATE_OWN','PROFILE_UPLOAD_AVATAR','PROFILE_UPLOAD_FULL_PHOTO','USER_STATS_READ',
    'TOURNAMENT_READ','TOURNAMENT_CONFIRM_RULES','TOURNAMENT_VIEW_BRACKET','TOURNAMENT_VIEW_STANDINGS',
    'TEAM_READ','TEAM_VIEW_OWN',
    'INVITATION_READ','INVITATION_ACCEPT','INVITATION_REJECT',
    'MATCH_READ','RESULT_READ',
    'LINEUP_READ',
    'PAYMENT_REGISTER','PAYMENT_READ',
    'SANCTION_READ',
    'REPORT_READ_STATS','REPORT_READ_TOP_SCORERS','REPORT_READ_MATCH_HISTORY','REPORT_READ_PERFORMANCE',
    'NOTIFICATION_READ','NOTIFICATION_READ_COUNT','BACKEND_VALIDATE'
)
WHERE r.code = 'PLAYER'
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- =====================
-- 2. TORNEOS
-- =====================

CREATE TABLE IF NOT EXISTS tournaments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    start_date DATE,
    end_date DATE,
    team_count INTEGER,
    cost_per_team DOUBLE PRECISION,
    rules TEXT,
    sanction_rules TEXT,
    inscription_close_date DATE,
    created_by BIGINT,
    status VARCHAR(50),
    CONSTRAINT fk_tournament_creator FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS courts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    location VARCHAR(255),
    tournament_id BIGINT,
    CONSTRAINT fk_court_tournament FOREIGN KEY (tournament_id) REFERENCES tournaments(id)
);

CREATE TABLE IF NOT EXISTS tournament_dates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id BIGINT,
    description VARCHAR(255),
    event_date DATE,
    CONSTRAINT fk_tournament_date_tournament FOREIGN KEY (tournament_id) REFERENCES tournaments(id)
);

CREATE TABLE IF NOT EXISTS tournament_rules_confirmations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    confirmed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tournament_user_rules_confirmation UNIQUE (tournament_id, user_id),
    CONSTRAINT fk_rules_confirmation_tournament FOREIGN KEY (tournament_id) REFERENCES tournaments(id),
    CONSTRAINT fk_rules_confirmation_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- =====================
-- 3. EQUIPOS
-- =====================

CREATE TABLE IF NOT EXISTS teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    shield_url VARCHAR(255),
    uniform_colors VARCHAR(255),
    tournament_id BIGINT,
    captain_id BIGINT,
    CONSTRAINT fk_team_tournament FOREIGN KEY (tournament_id) REFERENCES tournaments(id),
    CONSTRAINT fk_team_captain FOREIGN KEY (captain_id) REFERENCES users(id)
);

-- Tabla de join para los jugadores del equipo (ElementCollection)
CREATE TABLE IF NOT EXISTS team_players (
    team_id BIGINT NOT NULL,
    player_id BIGINT,
    CONSTRAINT fk_team_players_team FOREIGN KEY (team_id) REFERENCES teams(id)
);

CREATE TABLE IF NOT EXISTS team_invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT,
    player_id BIGINT,
    status VARCHAR(50),
    sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    responded_at TIMESTAMP,
    CONSTRAINT fk_invitation_team FOREIGN KEY (team_id) REFERENCES teams(id),
    CONSTRAINT fk_invitation_player FOREIGN KEY (player_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT,
    receipt_url VARCHAR(255),
    status VARCHAR(50),
    reviewed_by BIGINT,
    comments VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_payment_team FOREIGN KEY (team_id) REFERENCES teams(id),
    CONSTRAINT fk_payment_reviewer FOREIGN KEY (reviewed_by) REFERENCES users(id)
);

-- =====================
-- 4. CLASIFICACION
-- =====================

CREATE TABLE IF NOT EXISTS standings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id BIGINT,
    team_id BIGINT,
    played INTEGER DEFAULT 0,
    won INTEGER DEFAULT 0,
    drawn INTEGER DEFAULT 0,
    lost INTEGER DEFAULT 0,
    goals_for INTEGER DEFAULT 0,
    goals_against INTEGER DEFAULT 0,
    goal_difference INTEGER DEFAULT 0,
    points INTEGER DEFAULT 0,
    CONSTRAINT fk_standing_tournament FOREIGN KEY (tournament_id) REFERENCES tournaments(id),
    CONSTRAINT fk_standing_team FOREIGN KEY (team_id) REFERENCES teams(id)
);

-- =====================
-- 5. PARTIDOS
-- =====================

CREATE TABLE IF NOT EXISTS matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id BIGINT,
    home_team_id BIGINT,
    away_team_id BIGINT,
    referee_id BIGINT,
    court_id BIGINT,
    match_date DATE,
    match_time TIME,
    phase VARCHAR(50),
    home_score INTEGER,
    away_score INTEGER,
    played BOOLEAN DEFAULT false,
    status VARCHAR(50) DEFAULT 'TO_ASSIGN',
    CONSTRAINT fk_match_tournament FOREIGN KEY (tournament_id) REFERENCES tournaments(id),
    CONSTRAINT fk_match_home_team FOREIGN KEY (home_team_id) REFERENCES teams(id),
    CONSTRAINT fk_match_away_team FOREIGN KEY (away_team_id) REFERENCES teams(id),
    CONSTRAINT fk_match_referee FOREIGN KEY (referee_id) REFERENCES users(id),
    CONSTRAINT fk_match_court FOREIGN KEY (court_id) REFERENCES courts(id)
);

CREATE TABLE IF NOT EXISTS elimination_brackets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id BIGINT,
    round VARCHAR(255),
    match_position INTEGER,
    match_id BIGINT UNIQUE,
    CONSTRAINT fk_bracket_tournament FOREIGN KEY (tournament_id) REFERENCES tournaments(id),
    CONSTRAINT fk_bracket_match FOREIGN KEY (match_id) REFERENCES matches(id)
);

CREATE TABLE IF NOT EXISTS lineups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT,
    team_id BIGINT,
    formation VARCHAR(255),
    CONSTRAINT fk_lineup_match FOREIGN KEY (match_id) REFERENCES matches(id),
    CONSTRAINT fk_lineup_team FOREIGN KEY (team_id) REFERENCES teams(id)
);

CREATE TABLE IF NOT EXISTS lineup_players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lineup_id BIGINT,
    player_id BIGINT,
    position_x INTEGER,
    position_y INTEGER,
    starter BOOLEAN DEFAULT false,
    CONSTRAINT fk_lineup_player_lineup FOREIGN KEY (lineup_id) REFERENCES lineups(id),
    CONSTRAINT fk_lineup_player_user FOREIGN KEY (player_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS match_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT,
    player_id BIGINT,
    team_id BIGINT,
    event_type VARCHAR(50),
    event_minute INTEGER,
    additional_minutes INTEGER DEFAULT 0,
    CONSTRAINT fk_event_match FOREIGN KEY (match_id) REFERENCES matches(id),
    CONSTRAINT fk_event_player FOREIGN KEY (player_id) REFERENCES users(id),
    CONSTRAINT fk_event_team FOREIGN KEY (team_id) REFERENCES teams(id)
);

CREATE TABLE IF NOT EXISTS match_possessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT UNIQUE,
    home_percentage INTEGER,
    away_percentage INTEGER,
    CONSTRAINT fk_possession_match FOREIGN KEY (match_id) REFERENCES matches(id)
);

-- Tabla embeddable para heatmap points
CREATE TABLE IF NOT EXISTS match_possession_heatmap (
    possession_id BIGINT NOT NULL,
    x DOUBLE PRECISION,
    y DOUBLE PRECISION,
    CONSTRAINT fk_heatmap_possession FOREIGN KEY (possession_id) REFERENCES match_possessions(id)
);

CREATE TABLE IF NOT EXISTS sanctions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id BIGINT,
    player_id BIGINT,
    match_id BIGINT,
    description VARCHAR(255),
    sanction_date DATE,
    suspended_matches INTEGER DEFAULT 0,
    CONSTRAINT fk_sanction_tournament FOREIGN KEY (tournament_id) REFERENCES tournaments(id),
    CONSTRAINT fk_sanction_player FOREIGN KEY (player_id) REFERENCES users(id),
    CONSTRAINT fk_sanction_match FOREIGN KEY (match_id) REFERENCES matches(id)
);

-- =====================
-- 6. TABLA DE FLYWAY (para que Flyway no falle al conectar)
-- =====================
-- Nota: Flyway creara su tabla flyway_schema_history automaticamente.
-- Si usas Flyway con baseline-on-migrate=true, no necesitas crearla manualmente.

-- =============================================================
-- 7. DATOS DE PRUEBA
-- Password de todos los usuarios: "password123" (BCrypt)
-- =============================================================

INSERT INTO users (first_name, last_name, username, email, password, identification, role, user_type, program, active, created_at) VALUES
-- ADMINISTRADOR
('Juan',      'Admin Lopez',       'admin',               'admin@escuelaing.edu.co',                        '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', '1001234567', 'ADMINISTRATOR', 'PROFESSOR', 'SYSTEMS_ENGINEERING',                 true, '2026-01-15 08:00:00'),
-- ARBITROS
('Carlos',    'Arbitro Perez',     'arbitro1',            'arbitro1@escuelaing.edu.co',                     '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', '1009876543', 'REFEREE',       'PROFESSOR', 'ECONOMICS',                           true, '2026-01-20 10:00:00'),
('Ana',       'Arbitro Rodriguez', 'arbitro2',            'arbitro2@escuelaing.edu.co',                     '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', '1005551234', 'REFEREE',       'ADMINISTRATIVE', 'BUSINESS_ADMINISTRATION',         true, '2026-01-20 10:30:00'),
-- CAPITANES
('Pedro',     'Capitan Garcia',    'capitan.ingenieros',  'capitan.ingenieros@mail.escuelaing.edu.co',      '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', '2020134001', 'CAPTAIN',       'STUDENT',    'SYSTEMS_ENGINEERING',                 true, '2026-02-01 09:00:00'),
('Maria',     'Capitan Torres',    'capitan.byte',        'capitan.byte@mail.escuelaing.edu.co',            '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', '2020134002', 'CAPTAIN',       'STUDENT',    'ARTIFICIAL_INTELLIGENCE_ENGINEERING', true, '2026-02-01 09:30:00'),
-- JUGADORES Equipo 1: Ingenieros FC
('Andres',    'Delantero Ruiz',    'andres.ruiz',         'andres.ruiz@mail.escuelaing.edu.co',             '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', '2021134001', 'PLAYER',        'STUDENT',    'SYSTEMS_ENGINEERING',                 true, '2026-02-05 14:00:00'),
('Luis',      'Mediocampo Diaz',   'luis.diaz',           'luis.diaz@mail.escuelaing.edu.co',               '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', '2021134002', 'PLAYER',        'STUDENT',    'CYBERSECURITY_ENGINEERING',           true, '2026-02-05 14:30:00'),
('Sofia',     'Defensa Martinez',  'sofia.martinez',      'sofia.martinez@mail.escuelaing.edu.co',          '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', '2022134001', 'PLAYER',        'STUDENT',    'STATISTICS_ENGINEERING',              true, '2026-02-06 08:00:00'),
('Diego',     'Portero Gomez',     'diego.gomez',         'diego.gomez@mail.escuelaing.edu.co',             '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', '2022134002', 'PLAYER',        'STUDENT',    'SYSTEMS_ENGINEERING',                 true, '2026-02-06 08:30:00'),
-- JUGADORES Equipo 2: Byte United
('Valentina', 'Goleadora Rios',    'valentina.rios',      'valentina.rios@mail.escuelaing.edu.co',          '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', '2020134003', 'PLAYER',        'STUDENT',    'ARTIFICIAL_INTELLIGENCE_ENGINEERING', true, '2026-02-07 10:00:00'),
('Sebastian', 'Volante Castro',    'sebastian.castro',    'sebastian.castro@mail.escuelaing.edu.co',        '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', '2021134003', 'PLAYER',        'STUDENT',    'CYBERSECURITY_ENGINEERING',           true, '2026-02-07 10:30:00'),
('Camila',    'Central Herrera',   'camila.herrera',      'camila.herrera@mail.escuelaing.edu.co',          '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', '2022134003', 'PLAYER',        'STUDENT',    'STATISTICS_ENGINEERING',              true, '2026-02-07 11:00:00'),
('Felipe',    'Arquero Mora',      'felipe.mora',         'felipe.mora@mail.escuelaing.edu.co',             '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', '2023134001', 'PLAYER',        'STUDENT',    'ARTIFICIAL_INTELLIGENCE_ENGINEERING', true, '2026-02-07 11:30:00')
ON CONFLICT (email) DO NOTHING;

-- =============================================================
-- FIN DEL SCHEMA + DATOS
-- Total tablas: 24 (+ 2 tablas de join/embeddable)
-- Total usuarios de prueba: 13
-- Password de todos: password123
-- =============================================================
