CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50),
    user_type VARCHAR(50),
    program VARCHAR(100),
    identification VARCHAR(255),
    relationship_type VARCHAR(255),
    relationship_description VARCHAR(500),
    avatar_url VARCHAR(1024),
    active BOOLEAN DEFAULT true,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sport_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    position VARCHAR(50),
    secondary_position VARCHAR(50),
    dominant_foot VARCHAR(20),
    program VARCHAR(100),
    jersey_number INTEGER,
    photo_url VARCHAR(255),
    full_photo_url VARCHAR(1024),
    available BOOLEAN DEFAULT true,
    semester INTEGER,
    gender VARCHAR(50),
    age INTEGER,
    last_availability_change TIMESTAMP,
    availability_change_reason VARCHAR(255),
    CONSTRAINT fk_sport_profile_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS verification_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    verified_at TIMESTAMP,
    verified BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT fk_verification_token_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP,
    used BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT fk_password_reset_token_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS revoked_refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(2048) NOT NULL UNIQUE,
    revoked_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- =====================
-- 2. TORNEOS
-- =====================

CREATE TABLE IF NOT EXISTS tournaments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    start_date DATE,
    end_date DATE,
    team_count INTEGER,
    cost_per_team DOUBLE PRECISION,
    rules TEXT,
    sanction_rules TEXT,
    inscription_close_date DATE,
    created_by BIGINT,
    status VARCHAR(50),
    CONSTRAINT fk_tournament_creator FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS courts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    location VARCHAR(255),
    tournament_id BIGINT,
    CONSTRAINT fk_court_tournament FOREIGN KEY (tournament_id) REFERENCES tournaments(id)
);

CREATE TABLE IF NOT EXISTS tournament_dates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id BIGINT,
    description VARCHAR(255),
    event_date DATE,
    CONSTRAINT fk_tournament_date_tournament FOREIGN KEY (tournament_id) REFERENCES tournaments(id)
);

CREATE TABLE IF NOT EXISTS tournament_rules_confirmations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    confirmed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_tournament_user_rules_confirmation UNIQUE (tournament_id, user_id),
    CONSTRAINT fk_rules_confirmation_tournament FOREIGN KEY (tournament_id) REFERENCES tournaments(id),
    CONSTRAINT fk_rules_confirmation_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- =====================
-- 3. EQUIPOS
-- =====================

CREATE TABLE IF NOT EXISTS teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    shield_url VARCHAR(255),
    uniform_colors VARCHAR(255),
    tournament_id BIGINT,
    captain_id BIGINT,
    CONSTRAINT fk_team_tournament FOREIGN KEY (tournament_id) REFERENCES tournaments(id),
    CONSTRAINT fk_team_captain FOREIGN KEY (captain_id) REFERENCES users(id)
);

-- Tabla de join para los jugadores del equipo (ElementCollection)
CREATE TABLE IF NOT EXISTS team_players (
    team_id BIGINT NOT NULL,
    player_id BIGINT,
    CONSTRAINT fk_team_players_team FOREIGN KEY (team_id) REFERENCES teams(id)
);

CREATE TABLE IF NOT EXISTS team_invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT,
    player_id BIGINT,
    status VARCHAR(50),
    sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    responded_at TIMESTAMP,
    CONSTRAINT fk_invitation_team FOREIGN KEY (team_id) REFERENCES teams(id),
    CONSTRAINT fk_invitation_player FOREIGN KEY (player_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id BIGINT,
    receipt_url VARCHAR(255),
    status VARCHAR(50),
    reviewed_by BIGINT,
    comments VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_payment_team FOREIGN KEY (team_id) REFERENCES teams(id),
    CONSTRAINT fk_payment_reviewer FOREIGN KEY (reviewed_by) REFERENCES users(id)
);

-- =====================
-- 4. CLASIFICACION
-- =====================

CREATE TABLE IF NOT EXISTS standings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id BIGINT,
    team_id BIGINT,
    played INTEGER DEFAULT 0,
    won INTEGER DEFAULT 0,
    drawn INTEGER DEFAULT 0,
    lost INTEGER DEFAULT 0,
    goals_for INTEGER DEFAULT 0,
    goals_against INTEGER DEFAULT 0,
    goal_difference INTEGER DEFAULT 0,
    points INTEGER DEFAULT 0,
    CONSTRAINT fk_standing_tournament FOREIGN KEY (tournament_id) REFERENCES tournaments(id),
    CONSTRAINT fk_standing_team FOREIGN KEY (team_id) REFERENCES teams(id)
);

-- =====================
-- 5. PARTIDOS
-- =====================

CREATE TABLE IF NOT EXISTS matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id BIGINT,
    home_team_id BIGINT,
    away_team_id BIGINT,
    referee_id BIGINT,
    court_id BIGINT,
    match_date DATE,
    match_time TIME,
    phase VARCHAR(50),
    home_score INTEGER,
    away_score INTEGER,
    played BOOLEAN DEFAULT false,
    status VARCHAR(50) DEFAULT 'TO_ASSIGN',
    CONSTRAINT fk_match_tournament FOREIGN KEY (tournament_id) REFERENCES tournaments(id),
    CONSTRAINT fk_match_home_team FOREIGN KEY (home_team_id) REFERENCES teams(id),
    CONSTRAINT fk_match_away_team FOREIGN KEY (away_team_id) REFERENCES teams(id),
    CONSTRAINT fk_match_referee FOREIGN KEY (referee_id) REFERENCES users(id),
    CONSTRAINT fk_match_court FOREIGN KEY (court_id) REFERENCES courts(id)
);

CREATE TABLE IF NOT EXISTS elimination_brackets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id BIGINT,
    round VARCHAR(255),
    match_position INTEGER,
    match_id BIGINT UNIQUE,
    CONSTRAINT fk_bracket_tournament FOREIGN KEY (tournament_id) REFERENCES tournaments(id),
    CONSTRAINT fk_bracket_match FOREIGN KEY (match_id) REFERENCES matches(id)
);

CREATE TABLE IF NOT EXISTS lineups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT,
    team_id BIGINT,
    formation VARCHAR(255),
    CONSTRAINT fk_lineup_match FOREIGN KEY (match_id) REFERENCES matches(id),
    CONSTRAINT fk_lineup_team FOREIGN KEY (team_id) REFERENCES teams(id)
);

CREATE TABLE IF NOT EXISTS lineup_players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lineup_id BIGINT,
    player_id BIGINT,
    position_x INTEGER,
    position_y INTEGER,
    starter BOOLEAN DEFAULT false,
    CONSTRAINT fk_lineup_player_lineup FOREIGN KEY (lineup_id) REFERENCES lineups(id),
    CONSTRAINT fk_lineup_player_user FOREIGN KEY (player_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS match_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT,
    player_id BIGINT,
    team_id BIGINT,
    event_type VARCHAR(50),
    event_minute INTEGER,
    additional_minutes INTEGER DEFAULT 0,
    CONSTRAINT fk_event_match FOREIGN KEY (match_id) REFERENCES matches(id),
    CONSTRAINT fk_event_player FOREIGN KEY (player_id) REFERENCES users(id),
    CONSTRAINT fk_event_team FOREIGN KEY (team_id) REFERENCES teams(id)
);

CREATE TABLE IF NOT EXISTS match_possessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT UNIQUE,
    home_percentage INTEGER,
    away_percentage INTEGER,
    CONSTRAINT fk_possession_match FOREIGN KEY (match_id) REFERENCES matches(id)
);

-- Tabla embeddable para heatmap points
CREATE TABLE IF NOT EXISTS match_possession_heatmap (
    possession_id BIGINT NOT NULL,
    x DOUBLE PRECISION,
    y DOUBLE PRECISION,
    CONSTRAINT fk_heatmap_possession FOREIGN KEY (possession_id) REFERENCES match_possessions(id)
);

CREATE TABLE IF NOT EXISTS sanctions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id BIGINT,
    player_id BIGINT,
    match_id BIGINT,
    description VARCHAR(255),
    sanction_date DATE,
    suspended_matches INTEGER DEFAULT 0,
    CONSTRAINT fk_sanction_tournament FOREIGN KEY (tournament_id) REFERENCES tournaments(id),
    CONSTRAINT fk_sanction_player FOREIGN KEY (player_id) REFERENCES users(id),
    CONSTRAINT fk_sanction_match FOREIGN KEY (match_id) REFERENCES matches(id)
);