logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    edu.dosw.proyecto.Tech_Cup_Football_2026_1: WARN

  file:
    name: logs/aplicacion.log

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

