spring.application.name=Tech-Cup-DOSW-BackEnd-2026-1

spring.data.mongodb.uri=mongodb+srv://techcup_user:LaGuerita@cluster0.cd1w0oz.mongodb.net/techcup_db?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=techcup_db
spring.data.mongodb.auto-index-creation=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server.port=8080
server.address=0.0.0.0
spring.jackson.time-zone=America/Bogota
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true