package eci.edu.co.Tech_Cup_DOSW_BackEnd_2026_1.core.enums;

public enum Permission {
    // 1. AUTHENTICATION & SESSION
    AUTH_REGISTER,
    AUTH_LOGIN,
    AUTH_LOGOUT,
    AUTH_REFRESH_TOKEN,
    AUTH_RECOVER_PASSWORD,
    AUTH_VERIFY_EMAIL,

    // 2. USERS & PROFILES
    USER_READ,
    USER_CREATE,
    USER_UPDATE,
    USER_DELETE,
    USER_ASSIGN_ROLE,
    PROFILE_READ_OWN,
    PROFILE_UPDATE_OWN,
    PROFILE_UPLOAD_AVATAR,
    PROFILE_UPLOAD_FULL_PHOTO,
    USER_STATS_READ,

    // 3. TOURNAMENTS
    TOURNAMENT_CREATE,
    TOURNAMENT_UPDATE,
    TOURNAMENT_DELETE,
    TOURNAMENT_READ,
    TOURNAMENT_CONFIRM_RULES,
    TOURNAMENT_VIEW_BRACKET,
    TOURNAMENT_VIEW_STANDINGS,

    // 4. TEAMS
    TEAM_CREATE,
    TEAM_UPDATE,
    TEAM_DELETE,
    TEAM_READ,
    TEAM_MANAGE_PLAYERS,
    TEAM_VIEW_OWN,

    // 5. INVITATIONS
    INVITATION_READ,
    INVITATION_SEND,
    INVITATION_ACCEPT,
    INVITATION_REJECT,
    INVITATION_DELETE,

    // 6. MATCHES
    MATCH_CREATE,
    MATCH_UPDATE,
    MATCH_DELETE,
    MATCH_READ,
    MATCH_CHANGE_STATUS,

    // 7. RESULTS & EVENTS
    RESULT_REGISTER,
    GOAL_REGISTER,
    CARD_REGISTER,
    POSSESSION_REGISTER,
    RESULT_READ,

    // 8. LINEUPS
    LINEUP_CREATE,
    LINEUP_UPDATE,
    LINEUP_DELETE,
    LINEUP_READ,

    // 9. PAYMENTS
    PAYMENT_REGISTER,
    PAYMENT_READ,
    PAYMENT_UPDATE,
    PAYMENT_DELETE,

    // 10. SANCTIONS
    SANCTION_CREATE,
    SANCTION_UPDATE,
    SANCTION_DELETE,
    SANCTION_READ,

    // 11. REPORTS & STATISTICS
    REPORT_READ_STATS,
    REPORT_READ_TOP_SCORERS,
    REPORT_READ_MATCH_HISTORY,
    REPORT_READ_PERFORMANCE,

    // 12. NOTIFICATIONS
    NOTIFICATION_READ,
    NOTIFICATION_READ_COUNT,
    NOTIFICATION_SEND_EMAIL,

    // 13. ADMINISTRATION & SECURITY
    AUDIT_READ,
    AUDIT_DELETE,
    SYSTEM_MANAGE,
    BACKEND_VALIDATE,
    ACCESS_CONTROL_MANAGE
}
