package eci.edu.co.Tech_Cup_DOSW_BackEnd_2026_1.core.enums;

public enum Program {
    SYSTEMS_ENGINEERING,
    AI_ENGINEERING,
    CYBERSECURITY_ENGINEERING,
    STATISTICS_ENGINEERING,
    INFORMATION_MANAGEMENT_MASTERS,
    INFORMATICS_MASTERS,
    DATA_SCIENCE_MASTERS,
    OTHER
}
