package eci.edu.co.Tech_Cup_DOSW_BackEnd_2026_1.core.enums;

public enum Program {
    ARTIFICIAL_INTELLIGENCE_ENGINEERING,
    BIOTECHNOLOGY_ENGINEERING,
    CYBERSECURITY_ENGINEERING,
    CIVIL_ENGINEERING,
    SYSTEMS_ENGINEERING,
    INDUSTRIAL_ENGINEERING,
    ELECTRONICS_ENGINEERING,
    MECHANICAL_ENGINEERING,
    ELECTRICAL_ENGINEERING,
    ENVIRONMENTAL_ENGINEERING,
    BIOMEDICAL_ENGINEERING,
    STATISTICS_ENGINEERING,
    ECONOMICS,
    BUSINESS_ADMINISTRATION,
    MATHEMATICS
}
