-- =============================================================
-- V20260417_01 - Tabla de cedulas autorizadas para roles privilegiados
-- Requerida por el proceso de registro de ADMINISTRATOR, REFEREE, ORGANIZER
-- =============================================================

CREATE TABLE IF NOT EXISTS allowed_identifications (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identification  VARCHAR(255) NOT NULL UNIQUE,
    allowed_role    VARCHAR(50)  NOT NULL,
    used            BOOLEAN      NOT NULL DEFAULT false,
    created_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);
