-- =============================================================
-- V20260415_02 - RBAC: roles, permisos y asignaciones por rol
-- =============================================================

CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(80) NOT NULL UNIQUE,
    module VARCHAR(60) NOT NULL,
    description VARCHAR(255),
    active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE,
    CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
);

INSERT INTO roles (code, name, description) VALUES
('PLAYER', 'Jugador', 'Participante del torneo con acceso limitado a sus propios recursos'),
('CAPTAIN', 'Capitan', 'Jugador con permisos de gestion sobre su equipo'),
('ORGANIZER', 'Organizador', 'Gestion operativa del torneo y sus configuraciones'),
('REFEREE', 'Arbitro', 'Gestion de actas, eventos y sanciones en partidos'),
('ADMINISTRATOR', 'Administrador', 'Control total del sistema y de permisos')
ON CONFLICT (code) DO NOTHING;

INSERT INTO permissions (code, module, description) VALUES
('AUTH_REGISTER', 'AUTH', 'Registrar usuarios'),
('AUTH_LOGIN', 'AUTH', 'Iniciar sesion'),
('AUTH_LOGOUT', 'AUTH', 'Cerrar sesion'),
('AUTH_REFRESH_TOKEN', 'AUTH', 'Renovar token de acceso'),
('AUTH_RECOVER_PASSWORD', 'AUTH', 'Recuperar contrasena'),
('AUTH_VERIFY_EMAIL', 'AUTH', 'Verificar correo'),
('USER_READ', 'USER', 'Consultar usuarios'),
('USER_CREATE', 'USER', 'Crear usuarios'),
('USER_UPDATE', 'USER', 'Actualizar usuarios'),
('USER_DELETE', 'USER', 'Eliminar usuarios'),
('USER_ASSIGN_ROLE', 'USER', 'Asignar rol de usuario'),
('PROFILE_READ_OWN', 'PROFILE', 'Consultar perfil propio'),
('PROFILE_UPDATE_OWN', 'PROFILE', 'Actualizar perfil propio'),
('PROFILE_UPLOAD_AVATAR', 'PROFILE', 'Cargar avatar'),
('PROFILE_UPLOAD_FULL_PHOTO', 'PROFILE', 'Cargar foto de cuerpo completo'),
('USER_STATS_READ', 'PROFILE', 'Consultar estadisticas de usuario'),
('TOURNAMENT_CREATE', 'TOURNAMENT', 'Crear torneo'),
('TOURNAMENT_UPDATE', 'TOURNAMENT', 'Actualizar torneo'),
('TOURNAMENT_DELETE', 'TOURNAMENT', 'Eliminar torneo'),
('TOURNAMENT_READ', 'TOURNAMENT', 'Consultar torneos'),
('TOURNAMENT_CONFIRM_RULES', 'TOURNAMENT', 'Confirmar reglas de torneo'),
('TOURNAMENT_VIEW_BRACKET', 'TOURNAMENT', 'Consultar llaves de eliminacion'),
('TOURNAMENT_VIEW_STANDINGS', 'TOURNAMENT', 'Consultar tabla de posiciones'),
('TEAM_CREATE', 'TEAM', 'Crear equipo'),
('TEAM_UPDATE', 'TEAM', 'Actualizar equipo'),
('TEAM_DELETE', 'TEAM', 'Eliminar equipo'),
('TEAM_READ', 'TEAM', 'Consultar equipos'),
('TEAM_MANAGE_PLAYERS', 'TEAM', 'Gestionar jugadores de equipo'),
('TEAM_VIEW_OWN', 'TEAM', 'Consultar equipo propio'),
('INVITATION_READ', 'INVITATION', 'Consultar invitaciones'),
('INVITATION_SEND', 'INVITATION', 'Enviar invitaciones'),
('INVITATION_ACCEPT', 'INVITATION', 'Aceptar invitaciones'),
('INVITATION_REJECT', 'INVITATION', 'Rechazar invitaciones'),
('INVITATION_DELETE', 'INVITATION', 'Eliminar invitaciones'),
('MATCH_CREATE', 'MATCH', 'Crear partido'),
('MATCH_UPDATE', 'MATCH', 'Actualizar partido'),
('MATCH_DELETE', 'MATCH', 'Eliminar partido'),
('MATCH_READ', 'MATCH', 'Consultar partidos'),
('MATCH_CHANGE_STATUS', 'MATCH', 'Cambiar estado de partido'),
('RESULT_REGISTER', 'RESULT', 'Registrar resultado'),
('GOAL_REGISTER', 'RESULT', 'Registrar goles'),
('CARD_REGISTER', 'RESULT', 'Registrar tarjetas'),
('POSSESSION_REGISTER', 'RESULT', 'Registrar posesion'),
('RESULT_READ', 'RESULT', 'Consultar resultados'),
('LINEUP_CREATE', 'LINEUP', 'Crear alineacion'),
('LINEUP_UPDATE', 'LINEUP', 'Actualizar alineacion'),
('LINEUP_DELETE', 'LINEUP', 'Eliminar alineacion'),
('LINEUP_READ', 'LINEUP', 'Consultar alineaciones'),
('PAYMENT_REGISTER', 'PAYMENT', 'Registrar pago'),
('PAYMENT_READ', 'PAYMENT', 'Consultar pagos'),
('PAYMENT_UPDATE', 'PAYMENT', 'Actualizar pago'),
('PAYMENT_DELETE', 'PAYMENT', 'Eliminar pago'),
('SANCTION_CREATE', 'SANCTION', 'Crear sancion'),
('SANCTION_UPDATE', 'SANCTION', 'Actualizar sancion'),
('SANCTION_DELETE', 'SANCTION', 'Eliminar sancion'),
('SANCTION_READ', 'SANCTION', 'Consultar sanciones'),
('REPORT_READ_STATS', 'REPORT', 'Consultar estadisticas generales'),
('REPORT_READ_TOP_SCORERS', 'REPORT', 'Consultar goleadores'),
('REPORT_READ_MATCH_HISTORY', 'REPORT', 'Consultar historial de partidos'),
('REPORT_READ_PERFORMANCE', 'REPORT', 'Consultar rendimiento'),
('NOTIFICATION_READ', 'NOTIFICATION', 'Consultar notificaciones'),
('NOTIFICATION_READ_COUNT', 'NOTIFICATION', 'Consultar contador de notificaciones'),
('NOTIFICATION_SEND_EMAIL', 'NOTIFICATION', 'Enviar notificaciones por correo'),
('AUDIT_READ', 'ADMIN', 'Consultar auditoria'),
('AUDIT_DELETE', 'ADMIN', 'Eliminar auditoria'),
('SYSTEM_MANAGE', 'ADMIN', 'Gestionar parametros del sistema'),
('BACKEND_VALIDATE', 'ADMIN', 'Validaciones internas de backend'),
('ACCESS_CONTROL_MANAGE', 'ADMIN', 'Gestionar control de acceso')
ON CONFLICT (code) DO NOTHING;

-- ADMINISTRATOR = todos los permisos
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
CROSS JOIN permissions p
WHERE r.code = 'ADMINISTRATOR'
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- ORGANIZER
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code IN (
    'AUTH_REGISTER','AUTH_LOGIN','AUTH_LOGOUT','AUTH_REFRESH_TOKEN','AUTH_RECOVER_PASSWORD','AUTH_VERIFY_EMAIL',
    'USER_READ','USER_UPDATE','PROFILE_READ_OWN','PROFILE_UPDATE_OWN','PROFILE_UPLOAD_AVATAR','PROFILE_UPLOAD_FULL_PHOTO','USER_STATS_READ',
    'TOURNAMENT_CREATE','TOURNAMENT_UPDATE','TOURNAMENT_DELETE','TOURNAMENT_READ','TOURNAMENT_CONFIRM_RULES','TOURNAMENT_VIEW_BRACKET','TOURNAMENT_VIEW_STANDINGS',
    'TEAM_CREATE','TEAM_UPDATE','TEAM_DELETE','TEAM_READ','TEAM_MANAGE_PLAYERS','TEAM_VIEW_OWN',
    'INVITATION_READ','INVITATION_SEND','INVITATION_ACCEPT','INVITATION_REJECT','INVITATION_DELETE',
    'MATCH_CREATE','MATCH_UPDATE','MATCH_DELETE','MATCH_READ','MATCH_CHANGE_STATUS',
    'RESULT_REGISTER','POSSESSION_REGISTER','RESULT_READ',
    'PAYMENT_REGISTER','PAYMENT_READ','PAYMENT_UPDATE','PAYMENT_DELETE',
    'SANCTION_CREATE','SANCTION_UPDATE','SANCTION_READ',
    'REPORT_READ_STATS','REPORT_READ_TOP_SCORERS','REPORT_READ_MATCH_HISTORY','REPORT_READ_PERFORMANCE',
    'NOTIFICATION_READ','NOTIFICATION_READ_COUNT','NOTIFICATION_SEND_EMAIL',
    'AUDIT_READ','SYSTEM_MANAGE','BACKEND_VALIDATE'
)
WHERE r.code = 'ORGANIZER'
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- CAPTAIN
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code IN (
    'AUTH_REGISTER','AUTH_LOGIN','AUTH_LOGOUT','AUTH_REFRESH_TOKEN','AUTH_RECOVER_PASSWORD','AUTH_VERIFY_EMAIL',
    'USER_READ','USER_UPDATE','PROFILE_READ_OWN','PROFILE_UPDATE_OWN','PROFILE_UPLOAD_AVATAR','PROFILE_UPLOAD_FULL_PHOTO','USER_STATS_READ',
    'TOURNAMENT_READ','TOURNAMENT_CONFIRM_RULES','TOURNAMENT_VIEW_BRACKET','TOURNAMENT_VIEW_STANDINGS',
    'TEAM_CREATE','TEAM_UPDATE','TEAM_READ','TEAM_MANAGE_PLAYERS','TEAM_VIEW_OWN',
    'INVITATION_READ','INVITATION_SEND','INVITATION_ACCEPT','INVITATION_REJECT',
    'MATCH_READ','RESULT_READ',
    'LINEUP_CREATE','LINEUP_UPDATE','LINEUP_READ',
    'PAYMENT_READ','SANCTION_READ',
    'REPORT_READ_STATS','REPORT_READ_TOP_SCORERS','REPORT_READ_MATCH_HISTORY','REPORT_READ_PERFORMANCE',
    'NOTIFICATION_READ','NOTIFICATION_READ_COUNT','BACKEND_VALIDATE'
)
WHERE r.code = 'CAPTAIN'
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- REFEREE
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code IN (
    'AUTH_REGISTER','AUTH_LOGIN','AUTH_LOGOUT','AUTH_REFRESH_TOKEN','AUTH_RECOVER_PASSWORD','AUTH_VERIFY_EMAIL',
    'USER_READ','PROFILE_READ_OWN','PROFILE_UPDATE_OWN','PROFILE_UPLOAD_AVATAR','PROFILE_UPLOAD_FULL_PHOTO','USER_STATS_READ',
    'TOURNAMENT_READ','TOURNAMENT_CONFIRM_RULES','TOURNAMENT_VIEW_BRACKET','TOURNAMENT_VIEW_STANDINGS',
    'TEAM_READ','TEAM_VIEW_OWN',
    'INVITATION_READ',
    'MATCH_READ','MATCH_CHANGE_STATUS',
    'RESULT_REGISTER','GOAL_REGISTER','CARD_REGISTER','POSSESSION_REGISTER','RESULT_READ',
    'LINEUP_READ',
    'PAYMENT_READ',
    'SANCTION_CREATE','SANCTION_UPDATE','SANCTION_READ',
    'REPORT_READ_STATS','REPORT_READ_TOP_SCORERS','REPORT_READ_MATCH_HISTORY','REPORT_READ_PERFORMANCE',
    'NOTIFICATION_READ','NOTIFICATION_READ_COUNT','BACKEND_VALIDATE'
)
WHERE r.code = 'REFEREE'
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- PLAYER
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r
JOIN permissions p ON p.code IN (
    'AUTH_REGISTER','AUTH_LOGIN','AUTH_LOGOUT','AUTH_REFRESH_TOKEN','AUTH_RECOVER_PASSWORD','AUTH_VERIFY_EMAIL',
    'USER_READ','USER_UPDATE','PROFILE_READ_OWN','PROFILE_UPDATE_OWN','PROFILE_UPLOAD_AVATAR','PROFILE_UPLOAD_FULL_PHOTO','USER_STATS_READ',
    'TOURNAMENT_READ','TOURNAMENT_CONFIRM_RULES','TOURNAMENT_VIEW_BRACKET','TOURNAMENT_VIEW_STANDINGS',
    'TEAM_READ','TEAM_VIEW_OWN',
    'INVITATION_READ','INVITATION_ACCEPT','INVITATION_REJECT',
    'MATCH_READ','RESULT_READ',
    'LINEUP_READ',
    'PAYMENT_REGISTER','PAYMENT_READ',
    'SANCTION_READ',
    'REPORT_READ_STATS','REPORT_READ_TOP_SCORERS','REPORT_READ_MATCH_HISTORY','REPORT_READ_PERFORMANCE',
    'NOTIFICATION_READ','NOTIFICATION_READ_COUNT','BACKEND_VALIDATE'
)
WHERE r.code = 'PLAYER'
ON CONFLICT (role_id, permission_id) DO NOTHING;
