ALTER TABLE IF EXISTS users
    ADD COLUMN IF NOT EXISTS avatar_url VARCHAR(1024);

ALTER TABLE IF EXISTS sport_profiles
    ADD COLUMN IF NOT EXISTS secondary_position VARCHAR(50);

ALTER TABLE IF EXISTS sport_profiles
    ADD COLUMN IF NOT EXISTS dominant_foot VARCHAR(20);

ALTER TABLE IF EXISTS sport_profiles
    ADD COLUMN IF NOT EXISTS full_photo_url VARCHAR(1024);
