CREATE TABLE IF NOT EXISTS tournament_rules_confirmations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    confirmed_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_tournament_user_rules_confirmation UNIQUE (tournament_id, user_id)
);
